name: Scheduled Selenium Tests with Email Notification

on:
  schedule:
    - cron: "50 1 * * *"   # Runs daily at 01:50 AM UTC
  workflow_dispatch:       # Allows manual trigger from GitHub UI

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest pytest-html

      - name: Run tests and generate HTML report
        run: |
          pytest tests/test_login.py --html=report.html

      - name: Upload test report artifact
        uses: actions/upload-artifact@v3
        with:
          name: Test Report
          path: report.html

  notify:
    needs: test
    runs-on: ubuntu-latest
    if: success()  # Only send email if tests passed

    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Selenium Tests Passed ✅"
          body: "Your scheduled Selenium tests have successfully passed. Check GitHub Actions for details."
          to: chanduckd10@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          secure: true
